<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>ru.guchicraft</groupId><artifactId>guchicraft</artifactId><version>1.0.0-SNAPSHOT</version></parent><artifactId>builder</artifactId><dependencies><dependency><groupId>ru.guchicraft</groupId><artifactId>common</artifactId><version>${project.version}</version></dependency><dependency><groupId>org.openjfx</groupId><artifactId>javafx-controls</artifactId></dependency><dependency><groupId>com.google.code.gson</groupId><artifactId>gson</artifactId></dependency></dependencies><build><plugins><plugin><groupId>org.openjfx</groupId><artifactId>javafx-maven-plugin</artifactId><configuration><mainClass>ru.guchicraft.builder.BuilderApplication</mainClass></configuration></plugin></plugins></build></project>
